"""Simplified dealer schedule relationship

Revision ID: 190295b8d2e5
Revises: df408e24d8dc
Create Date: 2021-02-21 15:36:54.235523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190295b8d2e5'
down_revision = 'df408e24d8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_schedule',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=25), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('schedule_type', sa.String(length=25), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('modified_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealer_service',
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('modified_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dealer_id', 'service_id')
    )
    op.drop_table('dealer__service')
    op.drop_table('dealer__schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=25), nullable=False),
    sa.Column('open_time', sa.TIME(), nullable=True),
    sa.Column('close_time', sa.TIME(), nullable=True),
    sa.Column('created_datetime', sa.DATETIME(), nullable=True),
    sa.Column('modified_datetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealer__schedule',
    sa.Column('dealer_id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_type', sa.VARCHAR(length=25), nullable=False),
    sa.Column('created_datetime', sa.DATETIME(), nullable=True),
    sa.Column('modified_datetime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dealer_id', 'schedule_id')
    )
    op.create_table('dealer__service',
    sa.Column('dealer_id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.Column('created_datetime', sa.DATETIME(), nullable=True),
    sa.Column('modified_datetime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dealer_id', 'service_id')
    )
    op.drop_table('dealer_service')
    op.drop_table('dealer_schedule')
    # ### end Alembic commands ###
