"""Readded lat/lon columns

Revision ID: 973967230373
Revises: 9e7ff199714f
Create Date: 2021-02-27 22:21:33.894961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973967230373'
down_revision = '9e7ff199714f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer', sa.Column('latitude', sa.DECIMAL(), nullable=True))
    op.add_column('dealer', sa.Column('longitude', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer', 'longitude')
    op.drop_column('dealer', 'latitude')
    # ### end Alembic commands ###
